name: CI

on:
  push:
    branches:
      - master

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: npm ci
      env:
        CI: true
    - name: build and release
      run: |
        VERSION=$(awk '/version/{gsub(/("|",)/,"",$2);print $2};' package.json)
        if git rev-parse v$VERSION >/dev/null 2>&1; then
        echo "tag 'v$VERSION' already exists"
        else
        git config --global user.name 'ParkSB'
        git config --global user.email 'parkgds@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ParkSB/git-playground
        git checkout --detach
        mkdir dist
        echo "test file" > dist/test.dist
        sed -i '/dist/d' ./.gitignore
        git add .
        git commit -m "dist: $(date +'%Y-%m-%d %H:%M:%S')"
        git tag v$VERSION
        git push origin --tags
        fi
