name: PR Review D-Day Labeling

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Add D-Day Label to PRs
        run: |
          PR_LIST=$(gh pr list --json number,title,createdAt)
          DDAY_PR_ID_LIST=$(echo $PR_LIST | jq --arg NOW "$(date +%s)" 'map(. | { "n": .number, "d": ((.createdAt | fromdateiso8601) + (.title | match("\\(D-(\\d*)\\)$").captures[0].string | tonumber | (. - 1) * 86400) < ($NOW | tonumber)) }) | .[] | select(.d == true) | .n')
          echo $DDAY_PR_ID_LIST
          for PR_ID in $DDAY_PR_ID_LIST; do
            gh pr edit $PR_ID --add-label "d-day"
            sleep 1s
          done
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

